### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by Turqueso** [bludit/bludit#357]
I keep getting the same message
`{"status":"0","bludit":"Bludit API plugin","message":"Check the parameters"}`

**Comment by dignajar** [comment]
Have you the authorized key correctly?

**Comment by Turqueso** [comment]
if I click the link for Show all posts in the options, I should see a json with the posts, right? that's where I see the message.

**Comment by Turqueso** [comment]
This was fixed chatting on gitter and I see a commit changing a line in the API, but bludit.com still downloads a ziped version without the API fixed

**Comment by Sirjoseph94** [comment]
I have similar issue. Please how do I fix it

**Comment by dignajar** [comment]
@Sirjoseph94 Hi, what version of Bludit are you using ?

**Comment by Sirjoseph94** [comment]
1.5.2
I downloaded it from bludit.com few hours ago

**Comment by Sirjoseph94** [comment]
Any update on this API issue? am still getting "invalid token" error on v1.6

**Comment by dignajar** [comment]
Really ? I try it the last weekend and works, you are working with v1.6 beta 2 ? have you check the documentation ? how do you make the requests ?

**Comment by dignajar** [comment]
Bludit v2.0 released and new API.
https://docs-v2.bludit.com/en/api/introduction
